version: 0.2 
env:
  variable:
    ECR_REPO: "800990441904.dkr.ecr.us-east-1.amazonaws.com/roy/angular"
  # secrets-manager:
  #   DOCKERHUB_TOKEN: dockerhub:token
  #   DOCKERHUB_USERNAME: dockerhub:user
  systemsmanager:
    DOCKERHUB_TOKEN: /dockerhub/token
    DOCKERHUB_USERNAME: /dockerhub/username
phases: 
  pre_build:
    commands:
      - echo "hey its pre_build phase"
      - echo ${DOCKERHUB_TOKEN} | docker login -u ${DOCKERHUB_USERNAME} --password-stdin 
      # login into aws ecr 
      - echo "DOCKER LOGIN SUCCESSSFUL"
      # - AWS_MAIN_URI = "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com"
      - aws ecr get-login-password | docker login -u AWS --password-stdin ${ECR_REPO}
      - ecr_image = ${ECR_REPO}/my-angular-app:latest
  build:
    commands:
      - echo "build phase"
      - docker build -t my-angular-app:latest . 
  post_build:
    commands:
    - docker tag my-angular-app:latest ${DOCKERHUB_USERNAME}/my-angular-app:latest 
    - docker push ${DOCKERHUB_USERNAME}/my-angular-app:latest 
    # Image pushed to ecr 
    - docker tag my-angular-app:latest  ${ECR_REPO}/my-angular-app:latest
    - docker push ${ECR_REPO}/my-angular-app:latest