version: 0.2 
env:
  secrets-manager:
    DOCKERHUB_TOKEN: dockerhub:token
    DOCKERHUB_USERNAME: dockerhub:user
phases: 
  pre_build:
    commands:
      - echo "hey its pre_build phase"
      - echo ${DOCKERHUB_TOKEN} | docker login -u ${DOCKERHUB_USERNAME} --password-stdin 
  build:
    commands:
      - echo "build phase"
      - docker build -t my-angular-app:latest . 
  post_build:
    commands:
    - docker tag my-angular-app:latest ${DOCKERHUB_USERNAME}/my-angular-app:latest 
    - docker push ${DOCKERHUB_USERNAME}/my-angular-app:latest 